[toolchain]
anchor_version = "0.30.1"
package_manager = "yarn"

[features]
seeds = []
resolution = true
skip-lint = false

[programs.devnet]
deed_pre_tge = "BBcVjpdRKrtioVeoWRUp2QC88zZbhNWfVuyz6fXQ3Tms"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
